### ISSUE TITLE
Missing some things

### ISSUE THREAD

**Issue by lmorris99** [morshedalam/rename#3]
Ran it on my Rails 4 app: 
didn't change README title
didn't change database names
didn't change title and description in app/views/layouts/application.html.slim

helpful though!

**Comment by morshedalam** [comment]
@lmorris99 Thank you for using the lib and issue you raised.

- README title wasn't considered intentionally as it can replace similar word within a sentence. As for example an app name called Pull which can be used in a sentence as well. However, included again to exact match with module name.
- Database name is considered underscore separated module name only
- Included slim

Added considered file list into the readme
