### ISSUE TITLE
Project name conflicting with breeders model name

### ISSUE THREAD

**Issue by switters** [morshedalam/rename#4]
I propose to change the rails project name to 'myBreeder' (temp name) in order to migrate the name of what is currently the 'breedco' model to 'breeders'.

**Comment by morshedalam** [comment]
Thank you for using the lib and extremely sorry for not replying in time.. 

It was a fun to write the gem and didn't get time to work on this after initial build. Just went through your issue and tested and found no reason for the issue you reported. However, your issue has not been well described..

Just to let you, the gem is used to change the application name only not model even not looking other than configurable files of the application which means rename is not conflicting if you have same model name as well...

I think you are doing wrong anyway and can't explain properly. Closing the issue, create new issue with proper instruction if you experience any other issue.
