### ISSUE TITLE
rails 5 error

### ISSUE THREAD

**Issue by NanoMeko** [morshedalam/rename#7]
Running via Spring preloader in process 5582
Expected boolean default value for '--markerb'; got :erb (string)
Expected string default value for '--helper'; got true (boolean)
Expected string default value for '--assets'; got true (boolean)
Could not find generator 'rename:into'. Maybe you meant 'rename:app_to', 'generator' or 'devise:erb'
Run `rails generate --help` for more options.

**Comment by LimeBlast** [comment]
I'm getting this same error in Rails 3:

```
Could not find generator rename:into.
```

**Comment by morshedalam** [comment]
@NanoMeko Spring preloader warning is a know issue with Thor. Modified thor dependency which should fix the problem for rails >= 4. 

@LimeBlast I'll check with Rails 3 soon. What's the ruby version you are using?

**Comment by exocode** [comment]
`DISABLE_SPRING=1 rails generate rename:into Your-New-App-Name` works...
