### ISSUE TITLE
Just missing little small things when renaming ruby mine project

### ISSUE THREAD

**Issue by dexcell** [morshedalam/rename#9]
Run it on my rails 5, works amazing.
It even rename project name inside .idea directory since i'm using RubyMine.

However there is little things that it miss,
- Renaming .ideas/[project name].iml to .ideas/[new name].iml
- Files inside runConfiguration folder is also not renamed, however these files can be deleted and the IDE will recreate the new one.

Thanks

**Comment by morshedalam** [comment]
@dexcell Thank you for using the gem. You are right about the suggestion to remove IDE files, made the changes.
